config/routes.rb
  Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root "restaurants#index"

  resources :restaurants, shallow:true do
    resources :reviews do
      resources :endorsements
    end
  end

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :user

  has_many :reviews,
    -> { extending WithUserAssociationExtension },
    dependent: :destroy

  validates :name, length: { minimum: 3 }, uniqueness: true

  def average_rating
    return 'N/A' if reviews.none?
    reviews.average(:rating)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  has_many :endorsements
  belongs_to :restaurant
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already"}
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :restaurants
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]


   def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
     end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end
end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension

  def create_with_user(attributes ={}, user)
    attributes[:user] ||= user
    create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||=user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
  attributes[:user]||=user
  build(attributes)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

    def create
      @review = Review.find(params[:review_id])
      @review.endorsements.create
      render json: {new_endorsement_count: @review.endorsements.count}
    end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

before_action :authenticate_user!, :except => [:index, :show]

  def index
     @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    current_user.restaurants << @restaurant
      if @restaurant.save
        redirect_to restaurants_path
      else
        render 'new'
      end
    end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

  private

  def restaurant_params
     params.require(:restaurant).permit(:name, :description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build_with_user(review_params, current_user)

      if @review.save
        redirect_to restaurants_path, alert: 'You have successfully reviewed the restaurant'
      else
        if @review.errors[:user]
          redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
        else
          render :new
        end
      end
  end


    private

    def review_params
      params.require(:review).permit(:thoughts, :rating)
    end



end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
     # You need to implement the method below in your model (e.g. app/models/user.rb)
     @user = User.from_omniauth(request.env["omniauth.auth"])
     if @user.persisted?
       sign_in_and_redirect @user
       set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
     else
       session["devise.facebook_data"] = request.env["omniauth.auth"]
       redirect_to new_user_registration_url
     end
   end

   def failure
     redirect_to root_path
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%head
  %title YelpClone
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  %link{:href => "http://yui.yahooapis.com/pure/0.6.0/pure-min.css", :rel => "stylesheet"}

%body.pure-menu.pure-menu-horizontal
= notice
= alert
- if user_signed_in?
  = link_to "Sign out", destroy_user_session_path, method: :delete
- else
  = link_to "Sign in", new_user_session_path
  = link_to "Sign up", new_user_registration_path
  = link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path
= yield

app/views/restaurants/edit.html.haml
.pure-form
=form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_field :description
  = f.submit

app/views/restaurants/index.html.erb
<%if (user_signed_in?) && (@restaurants.any?) %>
  <%= link_to 'Add a restaurant', new_restaurant_path %>
  <br />
  <%@restaurants.each do |restaurant| %>
    <br />
    <%=link_to "#{restaurant.name}", restaurant_path(restaurant) %>
    <%restaurant.description%>
    <br />
      <%if current_user.id == restaurant.user_id%>
        <%=link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)%>
        <%=link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
      <%end%>
    <%=link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)%>
      <br /> <br />
      <%=restaurant.reviews.each do |review|%>
      <%=review.thoughts%>
      <%=review.rating%>
      <h3>Average rating: <%=restaurant.average_rating.to_i%></h3>
      <%=link_to "Endorse", review_endorsements_path(review), class: 'endorsements-link'%>
      <%= pluralize(review.endorsements.count, 'endorsement')%>
      <%end%>

  <%end%>

<%elsif @restaurants.any?%>
  <%@restaurants.each do |restaurant| %>
  <%=link_to "#{restaurant.name}", restaurant_path(restaurant)%>
  <%restaurant.description%>
  <h3>Average rating: <%=restaurant.average_rating.to_i%></h3>
  <%end%>
<%elsif user_signed_in?%>
<%= link_to 'Add a restaurant', new_restaurant_path %>
<br />
No restaurants yet!
<%else%>
  No restaurants yet!
<%end%>

app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2
      =pluralize @restaurant.errors.count, "error"
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |message|
        %li= message

.pure-form
  = form_for @restaurant do |f|
    = f.label :name
    = f.text_field :name
    = f.label :description
    = f.text_field :description
    = f.submit

app/views/restaurants/show.html.haml
%p= @restaurant.name
%p= @restaurant.description

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'